# Generated by Django 2.2.5 on 2021-09-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_auto_20210910_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedday',
            name='created',
            field=models.DateField(null=True,blank=True,auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bookedday',
            name='updated',
            field=models.DateField(null=True,blank=True,auto_now=True),
        ),
    ]
